# Links for the link blog.

[[links]]
title = "The Most Mario Colors"
description = "How do you spell \"MARIO\" with colors?"
url = "https://lmnt.me/blog/the-most-mario-colors.html"
date = "2025-02-22"

[[links]]
title = "Cognitive load is what matters"
description = "Complexity exists. Codebases tend towards entropy. How and where we manage that is what matters."
url = "https://minds.md/zakirullin/cognitive"
date = "2025-02-22"

[[links]]
title = "Every company should be sold to its employees"
description = "Cooperatives are really neat."
url = "https://www.elysian.press/p/employee-ownership"
date = "2025-02-22"

[[links]]
title = "Engineers don't make public squares. People do"
description = "> Decentralising social media isn’t a panacea for those problems - but it is ultimately a significant necessary component of resolving them."
url = "https://cpf.sh/blog/2025/01/25/engineers-dont-make-public-squares-people-do"
date = "2025-02-22"

[[links]]
title = "Invest in interfaces"
description = "Afterall, they're important."
url = "https://luke.hsiao.dev/blog/investing-in-interfaces/"
date = "2025-02-22"

[[links]]
title = "Other people’s problems"
description = "Why are your problems always harder to solve?"
url = "https://seths.blog/2024/04/other-peoples-problems/"
date = "2025-02-22"

[[links]]
title = "No one buys books"
description = "I wonder if if the new era of art accessibility and volume means that publishers will no longer be necessary?"
url = "https://www.elysian.press/p/no-one-buys-books"
date = "2025-02-22"

[[links]]
title = "The satoshi example"
description = "Giving something to the world--"
url = "https://www.jtwoodhouse.com/the-satoshi-example/"
date = "2025-02-22"

[[links]]
title = "Full Of Themselves"
description = "An analysis of title drops in movies."
url = "https://www.titledrops.net/"
date = "2025-02-22"

[[links]]
title = "The rowboat"
description = "> Seriously, what is the point of the internet if you can't share a link anymore?"
url = "https://www.jtwoodhouse.com/the-rowboat-theres-a-life-after-social-media/"
date = "2025-02-22"

[[links]]
title = "Range"
description = "Lack of content discoverability is a feature."
url = "https://lmnt.me/blog/range.html"
date = "2025-02-22"

[[links]]
title = "Making Small Games, Which Is Fun in Itself"
description = "> Creating small games is an enjoyable endeavor in itself."
url = "https://abagames.github.io/joys-of-small-game-development-en/fun_to_make_small_games.html"
date = "2025-02-22"

[[links]]
title = "How we Outsmarted CSGO Cheaters with IdentityLogger"
description = "An interesting approach to removing repeat-cheaters."
url = "https://mobeigi.com/blog/gaming/how-we-outsmarted-csgo-cheaters-with-identitylogger/"
date = "2025-02-22"

[[links]]
title = "File Over App: A Philosophy for Digital Longevity"
description = "> If you want to create digital artifacts that last, they must be files you can control, in formats that are easy to retrieve and read."
url = "https://rishikeshs.com/file-over-app/"
date = "2025-02-22"

[[links]]
title = "Unexpected Benefits of Building Your Own Tools"
description = "> And often, you will find that these tools will let you work in new and surprising ways."
url = "https://tiniuc.com/make-more-tools/"
date = "2025-02-22"

[[links]]
title = "A Cypherpunk's Manifesto"
description = "\"Cypherpunks write code.\""
url = "https://activism.net/cypherpunk/manifesto.html"
date = "2025-02-24"

[[links]]
title = "The Act of Creation"
description = "Everyone should create."
url = "https://sheep.horse/2025/1/the_act_of_creation.html"
date = "2025-02-26"

[[links]]
title = "how AWS S3 serves 1 petabyte per second on top of slow HDDs"
description = "S3 scaling is incredibly interesting."
url = "https://bigdata.2minutestreaming.com/p/how-aws-s3-scales-with-tens-of-millions-of-hard-drives"
date = "2025-09-25"

[[links]]
title = "Reflecting on a year of Gamedev in Zig"
description = "Pros and cons of Zig for gamedev in 2025."
url = "https://bgthompson.codeberg.page/blog/one-year-zig-gamedev-reflections/"
date = "2025-09-04"

[[links]]
title = "Get Weird and Disappear"
description = "> I Don't Need Permission To Swear"
url = "https://ludic.mataroa.blog/blog/get-weird-and-disappear/"
date = "2025-09-04"

[[links]]
title = "Stop Writing `__init__` Methods"
description = "Confusing constructors are not idiomatic."
url = "https://blog.glyph.im/2025/04/stop-writing-init-methods.html"
date = "2025-09-04"

[[links]]
title = "Majjit LSP"
description = "A VCS LSP is a great idea."
url = "https://matklad.github.io/2024/12/13/majjit-lsp.html"
date = "2025-10-01"

[[link]]
title = "Is Rust faster than C?"
description = "A different take on Rust vs C performance comparisons."
url = "https://steveklabnik.com/writing/is-rust-faster-than-c/"
date = "2025-11-23"

[[link]]
title = "Open Source Has Too Many Parasocial Relationships"
description = "> The essence of Free Software is: \"When it breaks, you get to keep both halves.\""
url = "https://pivotnine.com/blog/open-source-has-too-many-parasocial-relationships/"
date = "2025-12-02"

[[link]]
title = "You should feed the bots"
description = "Offense is the best defense."
url = "https://maurycyz.com/misc/the_cost_of_trash/"
date = "2025-12-06"

# [[link]]
# title = ""
# url = "https://feed-me-up-scotty.vincenttunru.com/"
